name: assignment
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: rootshell <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  sqljocky5: "^1.0.0"

dev_dependencies:
  test: ^0.12.0
